<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" ignored="0" total="5" passed="0">
  <reporter-output>
    <line>
      <![CDATA[<a href=Sun_Jun_07_21_31_23_IST_2020.jpg target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jun_07_21_31_23_IST_2020.jpg target="_blank"><img src=Sun_Jun_07_21_31_23_IST_2020.jpg height=200 width=200></a>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jun_07_21_31_26_IST_2020.jpg target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jun_07_21_31_26_IST_2020.jpg target="_blank"><img src=Sun_Jun_07_21_31_26_IST_2020.jpg height=200 width=200></a>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jun_07_21_31_29_IST_2020.jpg target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jun_07_21_31_29_IST_2020.jpg target="_blank"><img src=Sun_Jun_07_21_31_29_IST_2020.jpg height=200 width=200></a>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jun_07_21_31_31_IST_2020.jpg target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jun_07_21_31_31_IST_2020.jpg target="_blank"><img src=Sun_Jun_07_21_31_31_IST_2020.jpg height=200 width=200></a>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jun_07_21_31_34_IST_2020.jpg target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jun_07_21_31_34_IST_2020.jpg target="_blank"><img src=Sun_Jun_07_21_31_34_IST_2020.jpg height=200 width=200></a>]]>
    </line>
  </reporter-output>
  <suite name="Data Driven Test" duration-ms="13961" started-at="2020-06-07T16:01:20Z" finished-at="2020-06-07T16:01:34Z">
    <groups>
    </groups>
    <test name="Bank Manager Login Test" duration-ms="2620" started-at="2020-06-07T16:01:20Z" finished-at="2020-06-07T16:01:23Z">
      <class name="testcases.BankManagerLoginTest">
        <test-method status="FAIL" signature="loginTest()[pri:0, instance:testcases.BankManagerLoginTest@76b1e9b8]" name="loginTest" duration-ms="2222" started-at="2020-06-07T16:01:20Z" finished-at="2020-06-07T16:01:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Bank Manager Test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Bank Manager Test failed
at org.testng.Assert.fail(Assert.java:96)
at testcases.BankManagerLoginTest.loginTest(BankManagerLoginTest.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href=Sun_Jun_07_21_31_23_IST_2020.jpg target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href=Sun_Jun_07_21_31_23_IST_2020.jpg target="_blank"><img src=Sun_Jun_07_21_31_23_IST_2020.jpg height=200 width=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginTest -->
      </class> <!-- testcases.BankManagerLoginTest -->
    </test> <!-- Bank Manager Login Test -->
    <test name="Add Customer Test" duration-ms="8180" started-at="2020-06-07T16:01:23Z" finished-at="2020-06-07T16:01:32Z">
      <class name="testcases.AddCustomerTest">
        <test-method status="FAIL" signature="addCustomerTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.AddCustomerTest@79e4c792]" name="addCustomerTest" duration-ms="2579" started-at="2020-06-07T16:01:23Z" data-provider="dp" finished-at="2020-06-07T16:01:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Rahul]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Arora]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[A234234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Add Customer Test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Add Customer Test failed
at org.testng.Assert.fail(Assert.java:96)
at testcases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href=Sun_Jun_07_21_31_26_IST_2020.jpg target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href=Sun_Jun_07_21_31_26_IST_2020.jpg target="_blank"><img src=Sun_Jun_07_21_31_26_IST_2020.jpg height=200 width=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
        <test-method status="FAIL" signature="addCustomerTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.AddCustomerTest@79e4c792]" name="addCustomerTest" duration-ms="2321" started-at="2020-06-07T16:01:26Z" data-provider="dp" finished-at="2020-06-07T16:01:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Raman]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Arora]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[A24324]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Add Customer Test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Add Customer Test failed
at org.testng.Assert.fail(Assert.java:96)
at testcases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href=Sun_Jun_07_21_31_29_IST_2020.jpg target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href=Sun_Jun_07_21_31_29_IST_2020.jpg target="_blank"><img src=Sun_Jun_07_21_31_29_IST_2020.jpg height=200 width=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
        <test-method status="FAIL" signature="addCustomerTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.AddCustomerTest@79e4c792]" name="addCustomerTest" duration-ms="2260" started-at="2020-06-07T16:01:29Z" data-provider="dp" finished-at="2020-06-07T16:01:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Cory]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Paul]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[E34343]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Add Customer Test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Add Customer Test failed
at org.testng.Assert.fail(Assert.java:96)
at testcases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href=Sun_Jun_07_21_31_31_IST_2020.jpg target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href=Sun_Jun_07_21_31_31_IST_2020.jpg target="_blank"><img src=Sun_Jun_07_21_31_31_IST_2020.jpg height=200 width=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
      </class> <!-- testcases.AddCustomerTest -->
    </test> <!-- Add Customer Test -->
    <test name="Open Account Test" duration-ms="2772" started-at="2020-06-07T16:01:32Z" finished-at="2020-06-07T16:01:34Z">
      <class name="testcases.OpenAccountTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.OpenAccountTest@28261e8e]" name="setUp" is-config="true" duration-ms="12890" started-at="2020-06-07T16:01:07Z" finished-at="2020-06-07T16:01:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="openAccountTest(java.lang.String, java.lang.String)[pri:0, instance:testcases.OpenAccountTest@28261e8e]" name="openAccountTest" duration-ms="2448" started-at="2020-06-07T16:01:32Z" data-provider="dp" finished-at="2020-06-07T16:01:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Rahul Arora]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Rupee]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Open Account Test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Open Account Test failed
at org.testng.Assert.fail(Assert.java:96)
at testcases.OpenAccountTest.openAccountTest(OpenAccountTest.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href=Sun_Jun_07_21_31_34_IST_2020.jpg target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href=Sun_Jun_07_21_31_34_IST_2020.jpg target="_blank"><img src=Sun_Jun_07_21_31_34_IST_2020.jpg height=200 width=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- openAccountTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.OpenAccountTest@28261e8e]" name="tearDown" is-config="true" duration-ms="654" started-at="2020-06-07T16:01:34Z" finished-at="2020-06-07T16:01:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.OpenAccountTest -->
    </test> <!-- Open Account Test -->
  </suite> <!-- Data Driven Test -->
</testng-results>
